$base: http://jasapage.org/pgd_schema
$namespaces:
  sch: https://schema.org/
  efo: http://www.ebi.ac.uk/efo/
  obo: http://purl.obolibrary.org/obo/
  sio: http://semanticscience.org/resource/
  edam: http://edamontology.org/
  evs: http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#

$graph:

- name: sequenceSchema
  type: record
  fields:
    sequence_id:
      doc: Id of the sequence as defined by the authors
      type: string
      jsonldPredicate:
        _id: http://semanticscience.org/resource/SIO_000115
    sequence_database_accession:
      doc: If data is deposit at a public resource (e.g. Genbank, ENA) enter the Accession Id here. Please use a resolveable URL (e.g. http://identifiers.org/insdc/LC522350.1#sequence)
      type: string?
      jsonldPredicate:
          _id: http://edamontology.org/data_2091
          _type: "@id"
          noLinkCheck: true
    sequencing_technology:
      doc: Technology that was used to sequence this sample (e.g Sanger, Nanopor MiniION)
      type: string?
      jsonldPredicate:
        _id: http://purl.obolibrary.org/obo/NCIT_C172274
        _type: "@id"
        noLinkCheck: true
    sequencing_coverage:
      doc: Sequence coverage defined as the average number of reads representing a given nucleotide (e.g. [100]) - if multiple technologies were used multiple float values can be submitted e.g. [100, 20]
      type: double?
      jsonldPredicate:
        _id: http://purl.obolibrary.org/obo/NCIT_C155320

- name: methodSchema
  type: record
  fields:
    name:
      doc: Name of the method/workflow used to generate assembly or pangenome
      type: string
      jsonldPredicate:
        _id: http://semanticscience.org/resource/SIO_000116
    description:
      doc: Description of the method and command line options that were used to execute
      type: string?
      jsonldPredicate:
        _id: http://semanticscience.org/resource/SIO_000136
    version:
      doc: Version of the method
      type: string
      jsonldPredicate:
        _id: http://semanticscience.org/resource/SIO_000653
    

- name: assemblySchema
  type: record
  fields:
    assembly_id:
      doc: Id of the assembly as defined by the authors
      type: string
      jsonldPredicate:
        _id: http://semanticscience.org/resource/SIO_000115
    sequences:
      doc: Sequence reads
      type: sequenceSchema[]?
      jsonldPredicate:
        _id: http://purl.obolibrary.org/obo/SO_0000001
    assembly_version:
      doc: Version of the assembly
      type: string?
      jsonldPredicate:
        _id: http://semanticscience.org/resource/SIO_000653
    assembly_method:
      doc: Method used to assemble the genome
      type: methodSchema?
      jsonldPredicate:
        _id: http://semanticscience.org/resource/SIO_000098
    assembly_database_accession:
      doc: If data is deposit at a public resource (e.g. NCBI Genomes) enter the Accession Id here. Please use a resolveable URL (e.g. http://identifiers.org/insdc/LC522350.1#sequence)
      type: string?
      jsonldPredicate:
        _id: http://edamontology.org/data_2091
        _type: "@id"
        noLinkCheck: true
    additional_information:
      doc: Field for additional technology information
      type: string?
      jsonldPredicate:
        _id: http://semanticscience.org/resource/SIO_001167

- name: authorSchema
  type: record
  fields:
    author:
      doc: Name of the author
      type: string
      jsonldPredicate:
        _id: http://purl.obolibrary.org/obo/NCIT_C42781
    orcid:
      doc: ORCID ID of the author
      type: string?
      jsonldPredicate:
        _id: http://purl.obolibrary.org/obo/NCIT_C188272
    affiliation:
      doc: Name of the organization that author is affiliated with
      type: string?
      jsonldPredicate:
        _id: http://purl.obolibrary.org/obo/NCIT_C92453
    address:
      doc: Address of the affiliated organization
      type: string?
      jsonldPredicate:
        _id: http://semanticscience.org/resource/SIO_000172
    additional_information:
      doc: Field for additional author information
      type: string?
      jsonldPredicate:
        _id: http://semanticscience.org/resource/SIO_001167

- name: MainSchema
  type: record
  documentRoot: true
  fields:
    id:
      doc: The pangenome id
      type: string
      jsonldPredicate:
        _id: "@id"
        _type: "@id"
        noLinkCheck: true
    short_title:
      doc: The pangenome identifier provided by the authors
      type: string
      jsonldPredicate:
        _id: http://semanticscience.org/resource/SIO_000115
    title:
      doc: Pangenome title
      type: string
      jsonldPredicate:
        _id: http://semanticscience.org/resource/SIO_000185
    description:
      doc: Description
      type: string?
      jsonldPredicate:
        _id: http://semanticscience.org/resource/SIO_000136
    species:
      doc: Pangenome species as defined in NCBITaxon, e.g. http://purl.obolibrary.org/obo/NCBITaxon_9606 for Homo sapiens
      type: string
      jsonldPredicate:
        _id: http://purl.obolibrary.org/obo/NCIT_C45293
        _type: "@id"
        noLinkCheck: true
    target_population:
      doc: Population for which the pangenome is build
      type: string
      jsonldPredicate:
        _id: http://semanticscience.org/resource/SIO_001061
    number_samples:
      doc: Number of samples used in the pangenome
      type: int
      jsonldPredicate:
        _id: http://purl.obolibrary.org/obo/NCIT_C25337
    version:
      doc: Version of the pangenome
      type: string
      jsonldPredicate:
        _id: http://semanticscience.org/resource/SIO_000653
    reference:
      doc: Reference genome sequence
      type: assemblySchema?
      jsonldPredicate:
        _id: http://purl.obolibrary.org/obo/NCIT_C164388
    assemblies:
      doc: Assemblies that are used to build the pangenome
      type: assemblySchema[]
      jsonldPredicate:
        _id: http://purl.obolibrary.org/obo/NCIT_C73517
    method:
      doc: Method used to build the pangenome
      type: methodSchema
      jsonldPredicate:
        _id: http://semanticscience.org/resource/SIO_000098
    authors:
      doc: Authors of the pangenome
      type: authorSchema[]
      jsonldPredicate:
        _id: http://semanticscience.org/resource/SIO_001315
    publications:
      doc: Reference to publications of this pangenome (e.g. DOI, pubmed ID, ...)
      type: string[]?
      jsonldPredicate:
        _id: http://semanticscience.org/resource/SIO_000087
    website:
      doc: The project website or a github repository link
      type: string?
      jsonldPredicate:
        _id: http://semanticscience.org/resource/SIO_000296
        _type: "@id"
        noLinkCheck: true
    