$base: http://jasapage.org/pgd_schema
$namespaces:
  sch: https://schema.org/
  efo: http://www.ebi.ac.uk/efo/
  obo: http://purl.obolibrary.org/obo/
  sio: http://semanticscience.org/resource/
  edam: http://edamontology.org/
  evs: http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#

$graph:

- name: sequenceSchema
  type: record
  fields:
    sequence_id:
      doc: Id of the sequence as defined by the authors
      type: string
      jsonldPredicate:
        _id: http://semanticscience.org/resource/SIO_000115
    sequence_database_accession:
      doc: If data is deposit at a public resource (e.g. Genbank, ENA) enter the Accession Id here. Please use a resolveable URL (e.g. http://identifiers.org/insdc/LC522350.1#sequence)
      type: string[]?
      jsonldPredicate:
          _id: http://edamontology.org/data_2091
          _type: "@id"
          noLinkCheck: true
    sequencing_technology:
      doc: Technology that was used to sequence this sample (e.g Sanger, Nanopor MiniION)
      type: string[]?
      jsonldPredicate:
        _id: http://purl.obolibrary.org/obo/NCIT_C172274
        _type: "@id"
        noLinkCheck: true
    sequencing_coverage:
      doc: Sequence coverage defined as the average number of reads representing a given nucleotide (e.g. [100]) - if multiple technologies were used multiple float values can be submitted e.g. [100, 20]
      type: double[]?
      jsonldPredicate:
        _id: http://purl.obolibrary.org/obo/NCIT_C155320

- name: assemblySchema
  type: record
  fields:
    assembly_id:
      doc: Id of the assembly as defined by the authors
      type: string
      jsonldPredicate:
        _id: http://semanticscience.org/resource/SIO_000115
    sequences: sequenceSchema[]?
    assembly_version:
      doc: Version of the assembly
      type: string
      jsonldPredicate:
        _id: https://schema.org/version
    assembly_method:
      doc: Protocol which provides instructions on the alignment of sequencing reads to reference genome
      type: string?
      jsonldPredicate:
        _id: http://www.ebi.ac.uk/efo/EFO_0002699
    assembly_database_accession:
      doc: If data is deposit at a public resource (e.g. NCBI Genomes) enter the Accession Id here. Please use a resolveable URL (e.g. http://identifiers.org/insdc/LC522350.1#sequence)
      type: string?
      jsonldPredicate:
          _id: http://edamontology.org/data_2091
          _type: "@id"
          noLinkCheck: true
    additional_information:
      doc: Field for additional technology information
      type: string?
      jsonldPredicate:
        _id: http://semanticscience.org/resource/SIO_001167

- name: authorSchema
  type: record
  fields:
    authors:
      doc: Name(s) of the author(s)
      type: string[]
      jsonldPredicate:
          _id: http://purl.obolibrary.org/obo/NCIT_C42781
    organization:
      doc: Name of the organization that build the pangenome
      type: string?
      jsonldPredicate:
          _id: http://purl.obolibrary.org/obo/NCIT_C92453
    address:
      doc: Address of the organization
      type: string?
      jsonldPredicate:
          _id: http://purl.obolibrary.org/obo/IAO_0000422
    publication:
      doc: Reference to publication of this sample (e.g. DOI, pubmed ID, ...)
      type: string?
      jsonldPredicate:
        _id: http://purl.obolibrary.org/obo/NCIT_C19026
    additional_authors_information:
      doc: Field for additional authors information
      type: string?
      jsonldPredicate:
        _id: http://semanticscience.org/resource/SIO_001167

- name: MainSchema
  type: record
  documentRoot: true
  fields:
    id:
      doc: The pangenome id
      type: string
      jsonldPredicate:
        _id: "@id"
        _type: "@id"
        noLinkCheck: true
    local_id:
      doc: The pangenome identifier provided by the authors
      type: string
      jsonldPredicate:
        _id: http://semanticscience.org/resource/SIO_000115
    title:
      doc: Pangenome name
      type: string
      jsonldPredicate:
        _id: https://schema.org/title
    description:
      doc: Description
      type: string?
      jsonldPredicate:
        _id: https://schema.org/description
    species:
      doc: Pangenome species as defined in NCBITaxon, e.g. http://purl.obolibrary.org/obo/NCBITaxon_9606 for Homo sapiens
      type: string
      jsonldPredicate:
        _id: http://www.ebi.ac.uk/efo/EFO_0000532
        _type: "@id"
        noLinkCheck: true
    target_population:
      doc: Population for which the pangenome is build
      type: string
      jsonldPredicate:
        _id: https://schema.org/targetPopulation
    version:
      doc: Version of the pangenome
      type: string
      jsonldPredicate:
        _id: https://schema.org/version
    reference: assemblySchema?
    assemblies: assemblySchema[]
    author: authorSchema
    website:
      doc: The project website or a github repository link
      type: string?
      jsonldPredicate:
        _id: https://schema.org/WebSite 
    